name: meow
channels:
  - conda-forge
dependencies:
  # required
  - loguru
  - matplotlib
  - numexpr
  - numpy>=1.22
  - orjson
  - pandas
  - pandas-stubs
  - pillow
  - pydantic
  - rich
  - scipy
  - shapely
  - tqdm
  - flatten-dict

  # pyproject.toml
  - build
  - pip<22
  - python=3.10
  - setuptools
  - wheel

  # dev
  - bumpversion
  - ca-certificates
  - certifi
  - docutils
  - flake8
  - ipykernel
  - ipyevents
  - ipympl
  - isort
  - jupyter-book
  - jupyter-sphinx
  - line_profiler
  - make
  - nbsphinx
  - nbstripout
  - openssl
  - papermill
  - pre-commit
  - pydata-sphinx-theme
  - pydocstyle
  - pytest
  - pytest-cov
  - recommonmark
  - sphinx
  - sphinx-book-theme
  - tox
  - twine

  # trimesh
  - lxml
  - networkx
  - pyglet
  - rtree
  - scipy
  - shapely
  - trimesh
  - xxhash

  # extra
  - gdsfactory>=6.27.0
  - jaxlib
  #- mpb
  #- nomkl
  #- pymeep=*=mpi_mpich_*

  - pip:
    # required
    - fastcore
    - fastprogress
    - sax>=0.8.4
    - triangle
    - tidy3d>=1.8.2

    # trimesh
    - trimesh[easy]
    - pyembree
    - mapbox-earcut

    # jax
    - jax
    # - klujax -> install problems

    # dev
    - autodoc-pydantic
    - myst-nb>=0.17.1

    # extra
    - klayout>=0.28.3
