name: main
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/main.yml"
      - "!.github/workflows/publish.yml"
      - "docs/**"
      - "*.md"
      - ".git*"

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: condaforge/mambaforge
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: |
          mamba install make papermill parallel ipyevents ipytree gdspy gdstk
      - name: Install meow
        run: pip install .[vis,jax,klu,ipy,gds,dev]
      - name: Run notebooks
        run: find examples -name "*.ipynb" -not -path "*/.ipynb_checkpoints/*" | xargs parallel papermill {} {} -k python3 ':::'
      - name: Expose 'examples' as artifact
        uses: actions/upload-artifact@master
        with:
          name: examples
          path: /github/workspace/examples

  docs:
    runs-on: ubuntu-latest
    needs:
      - run
    container:
      image: condaforge/mambaforge
      volumes:
        - ${{ github.workspace }}:/github/workspace
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: mamba install make
      - name: Download 'examples' artifact
        uses: actions/download-artifact@master
        with:
          name: examples
          path: ./examples
      - name: Install meow
        run: pip install .[vis,jax,klu,ipy,gds,dev]
      - name: Build docs
        run: make docs && touch docs/build/html/.nojekyll
      - name: Patch binder links
        run: find docs/build/html -name "*.html" | xargs sed -i 's|urlpath=tree/docs|urlpath=tree|g'
      - name: Patch colab links
        run: find docs/build/html -name "*.html" | xargs sed -i 's|/blob/main/docs/|/blob/main/|g'
      - name: Store artifacts
        uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs/build/html

  pages:
    runs-on: ubuntu-latest
    needs:
      - docs
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download 'docs' artifact
        uses: actions/download-artifact@master
        with:
          name: docs
          path: docs/build/html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: pages
          folder: docs/build/html
